### ISSUE TITLE
Getting error while try to use it in Node v16.13.2

### ISSUE THREAD

**Issue by alxkravchenko** [center-key/gulp-w3c-html-validator#9]
Error [ERR_REQUIRE_ESM]: require() of ES Module W:\training\just_validate\node_modules\w3c-html-validator\node_modules\chalk\source\index.js from W:\training\just_validate\node_modules\w3c-html-validator\dist\w3c-html-validator.umd.cjs not supported.
Instead change the require of index.js in W:\training\just_validate\node_modules\w3c-html-validator\dist\w3c-html-validator.umd.cjs to a dynamic import() which is available in all CommonJS modules.

**Comment by pilafmon** [comment]
Good news... **node v16.14.0** was just released today.

**Comment by alxkravchenko** [comment]
Updated to 16.14.0 but i have the same problem :(
I remember that this package worked perfect on my old system, but i dont remember which node version was installed. Or maybe node version is not the problem?

**Comment by pilafmon** [comment]
The version of **node** is probably not the issue.

While I don't yet have a solution, here are two possible workarounds:

**1)** Use the underlying **w3c-html-validator** library directly.
```
$ npm install --save-dev w3c-html-validator
```
Then kick off the validator from an **npm** script command instead of **gulp**.

**package.json**
```json
   "scripts": {
      "validate": "w3c-html-validator docs/*.html"
   },
```

**2)** Switch to ES Modules.

Add the following configuration line to your `package.json` file:
```
   "type": "module",
```
Then replace the old deprecated `require` statements with the new standard `import` statements.

Example `gulpfile.js` file with modern ES Modules:
https://github.com/center-key/clabe-validator/blob/main/gulpfile.js

**Comment by alxkravchenko** [comment]
Both of these workarounds work for me. Thank you!
